### ISSUE TITLE
Asciidoc 0.5.4rc and HEAD fails to start for hibernate.org

### ISSUE THREAD

**Issue by emmanuelbernard** [awestruct/awestruct#381]
github.com/hibernate/hibernate.org

changing to the 0.5.4rc or HEAD (bd7e1fbc)

I have the following error (HEAD)

```
emmanuel@dhcp-193-232 hibernate.org (master) $ ~/Code/others/awestruct/bin/awestruct --version                             
Awestruct: 0.5.4.dev
http://awestruct.org/
emmanuel@dhcp-193-232 hibernate.org (master) $ ~/Code/others/awestruct/bin/awestruct -d
Using profile: development
Generating site: http://localhost:4242
Skipping files cache update.
***************************************************************************
Starting preview server at http://localhost:4242 (Press Ctrl-C to shutdown)
***************************************************************************
/Users/emmanuel/Code/others/awestruct/lib/awestruct/cli/auto.rb:23:in `run': undefined method `change' for #<Listen::Listener:0x007fecab82d468> (NoMethodError)
        from /Users/emmanuel/Code/others/awestruct/lib/awestruct/cli/invoker.rb:121:in `invoke_auto'
        from /Users/emmanuel/Code/others/awestruct/lib/awestruct/cli/invoker.rb:50:in `invoke!'
        from /Users/emmanuel/Code/others/awestruct/bin/awestruct:9:in `<main>'
```

**Comment by hosein203** [comment]
v2rayng x-ray core 3.8
1اشعه ایکس

**Comment by hosein203** [comment]
v2rayng x-ray core 3.8
1اشعه ایکس

**Comment by hosein203** [comment]
v2rayng x-ray core 3.8
1اشعه ایکس

**Comment by hosein203** [comment]
v2rayng x-ray core 3.8
1اشعه ایکس

**Comment by hosein203** [comment]
v2rayng x-ray core 3.8
1اشعه ایکس

**Comment by hosein203** [comment]
v2rayng x-ray core 3.8
1اشعه ایکس
