### ISSUE TITLE
Libv8 install issues in OSX

### ISSUE THREAD

**Issue by galderz** [awestruct/awestruct#502]
I can run `bundle install` with awestruct 0.5.6 nor 0.5.7.RC2 on OSX 10.10.3. I'm getting this issue:

```
Installing libv8 3.11.8.17 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/g/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151203-60158-qvn2j1.rb extconf.rb
creating Makefile
Compiling v8 for x64
Using python 2.7.10
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Using compiler: /usr/bin/g++
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
                 ^
1 error generated.
make[1]: *** [/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
make: *** [x64.release] Error 2
/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `each'
	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_can_use_vfp_instructions=true
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o

extconf failed, exit code 1

Gem files will remain installed in /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17 for inspection.
Results logged to /Users/g/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/libv8-3.11.8.17/gem_make.out
An error occurred while installing libv8 (3.11.8.17), and Bundler cannot continue.
Make sure that `gem install libv8 -v '3.11.8.17'` succeeds before bundling.
```

There's some suggestion on how to solve it in this [Stackoverflow thread](http://stackoverflow.com/questions/19577759/installing-libv8-gem-on-os-x-10-9) but none seem to work as expected.

I've tried to execute `gem install libv8 -- --with-system-v8` which works fine, but then when I execute `bundle install` it fails with:

```
Installing therubyracer 0.11.4 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/g/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151203-55902-1x8zkn1.rb extconf.rb
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
checking for v8.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/g/.rvm/rubies/ruby-2.2.1/bin/$(RUBY_BASE_NAME)
	--with-pthreadlib
	--without-pthreadlib
	--with-objclib
	--without-objclib
	--enable-debug
	--disable-debug
	--with-v8-dir
	--without-v8-dir
	--with-v8-include
	--without-v8-include=${v8-dir}/include
	--with-v8-lib
	--without-v8-lib=${v8-dir}/lib
/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:50:in `configure': You have chosen to use the version of V8 found on your system (Libv8::Location::System::NotFoundError)
and *not* the one that is bundle with the libv8 rubygem. However,
it could not be located. please make sure you have a version of
v8 that is compatible with 3.11.8.17 installed. You may
need to special --with-v8-dir options if it is in a non-standard
location

thanks,
The Mgmt

	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/lib/libv8.rb:7:in `configure_makefile'
	from extconf.rb:32:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/g/.rvm/gems/ruby-2.2.1/gems/therubyracer-0.11.4 for inspection.
Results logged to /Users/g/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/therubyracer-0.11.4/gem_make.out
An error occurred while installing therubyracer (0.11.4), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.
```

I've also tried to execute `gem install libv8 -v '3.11.8.17' -- --with-v8-lib` but fails with:

```
Building native extensions with: '--with-v8-lib'
This could take a while...
ERROR:  Error installing libv8:
	ERROR: Failed to build gem native extension.

    /Users/g/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151203-56138-1cutxrg.rb extconf.rb --with-v8-lib
creating Makefile
Compiling v8 for x64
Using python 2.7.10
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Using compiler: /usr/bin/g++
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
                 ^
1 error generated.
make[1]: *** [/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
make: *** [x64.release] Error 2
/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `each'
	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `verify_installation!'
	from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:26:in `install!'
	from extconf.rb:7:in `<main>'
GYP_GENERATORS=make \
	build/gyp/gyp --generator-output="out" build/all.gyp \
	              -Ibuild/standalone.gypi --depth=. \
	              -Dv8_target_arch=x64 \
	              -S.x64  -Dv8_can_use_vfp_instructions=true
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o

extconf failed, exit code 1

Gem files will remain installed in /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17 for inspection.
Results logged to /Users/g/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/libv8-3.11.8.17/gem_make.out
```

I checked what the latest `therubyracer` version is and that is `0.12.2`. I can install this version fine after executing `gem install libv8 -v '3.16.14.13' -- --with-v8-lib`, but those are not the versions that work for the current Awestruct version.

Any ideas?

**Comment by LightGuard** [comment]
What are you using therubyracer for? It shouldn't be a dependency for
awestruct.

On Thursday, December 3, 2015, Galder Zamarreño <notifications@github.com>
wrote:

> I can run bundle install with awestruct 0.5.6 nor 0.5.7.RC2 on OSX
> 10.10.3. I'm getting this issue:
>
> Installing libv8 3.11.8.17 with native extensions
>
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>
>     /Users/g/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151203-60158-qvn2j1.rb extconf.rb
> creating Makefile
> Compiling v8 for x64
> Using python 2.7.10
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Using compiler: /usr/bin/g++
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> ../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
> static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
>                  ^
> 1 error generated.
> make[1]: *** [/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
> make: *** [x64.release] Error 2
> /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `each'
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `verify_installation!'
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:26:in `install!'
>     from extconf.rb:7:in `<main>'
> GYP_GENERATORS=make \
>     build/gyp/gyp --generator-output="out" build/all.gyp \
>                   -Ibuild/standalone.gypi --depth=. \
>                   -Dv8_target_arch=x64 \
>                   -S.x64  -Dv8_can_use_vfp_instructions=true
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
>
> extconf failed, exit code 1
>
> Gem files will remain installed in /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17 for inspection.
> Results logged to /Users/g/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/libv8-3.11.8.17/gem_make.out
> An error occurred while installing libv8 (3.11.8.17), and Bundler cannot continue.
> Make sure that `gem install libv8 -v '3.11.8.17'` succeeds before bundling.
>
> There's some suggestion on how to solve it in this Stackoverflow thread
> <http://stackoverflow.com/questions/19577759/installing-libv8-gem-on-os-x-10-9>
> but none seem to work as expected.
>
> I've tried to execute gem install libv8 -- --with-system-v8 which works
> fine, but then when I execute bundle install it fails with:
>
> Installing therubyracer 0.11.4 with native extensions
>
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>
>     /Users/g/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151203-55902-1x8zkn1.rb extconf.rb
> checking for main() in -lpthread... yes
> checking for main() in -lobjc... yes
> checking for v8.h... no
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
>
> Provided configuration options:
>     --with-opt-dir
>     --without-opt-dir
>     --with-opt-include
>     --without-opt-include=${opt-dir}/include
>     --with-opt-lib
>     --without-opt-lib=${opt-dir}/lib
>     --with-make-prog
>     --without-make-prog
>     --srcdir=.
>     --curdir
>     --ruby=/Users/g/.rvm/rubies/ruby-2.2.1/bin/$(RUBY_BASE_NAME)
>     --with-pthreadlib
>     --without-pthreadlib
>     --with-objclib
>     --without-objclib
>     --enable-debug
>     --disable-debug
>     --with-v8-dir
>     --without-v8-dir
>     --with-v8-include
>     --without-v8-include=${v8-dir}/include
>     --with-v8-lib
>     --without-v8-lib=${v8-dir}/lib
> /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:50:in `configure': You have chosen to use the version of V8 found on your system (Libv8::Location::System::NotFoundError)
> and *not* the one that is bundle with the libv8 rubygem. However,
> it could not be located. please make sure you have a version of
> v8 that is compatible with 3.11.8.17 installed. You may
> need to special --with-v8-dir options if it is in a non-standard
> location
>
> thanks,
> The Mgmt
>
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/lib/libv8.rb:7:in `configure_makefile'
>     from extconf.rb:32:in `<main>'
>
> extconf failed, exit code 1
>
> Gem files will remain installed in /Users/g/.rvm/gems/ruby-2.2.1/gems/therubyracer-0.11.4 for inspection.
> Results logged to /Users/g/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/therubyracer-0.11.4/gem_make.out
> An error occurred while installing therubyracer (0.11.4), and Bundler cannot continue.
> Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.
>
> I've also tried to execute gem install libv8 -v '3.11.8.17' --
> --with-v8-lib but fails with:
>
> Building native extensions with: '--with-v8-lib'
> This could take a while...
> ERROR:  Error installing libv8:
>     ERROR: Failed to build gem native extension.
>
>     /Users/g/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20151203-56138-1cutxrg.rb extconf.rb --with-v8-lib
> creating Makefile
> Compiling v8 for x64
> Using python 2.7.10
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Using compiler: /usr/bin/g++
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> ../src/cached-powers.cc:136:18: error: unused variable 'kCachedPowersLength' [-Werror,-Wunused-const-variable]
> static const int kCachedPowersLength = ARRAY_SIZE(kCachedPowers);
>                  ^
> 1 error generated.
> make[1]: *** [/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o] Error 1
> make: *** [x64.release] Error 2
> /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:36:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/tools/gyp/libv8_base.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `each'
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:35:in `verify_installation!'
>     from /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/ext/libv8/location.rb:26:in `install!'
>     from extconf.rb:7:in `<main>'
> GYP_GENERATORS=make \
>     build/gyp/gyp --generator-output="out" build/all.gyp \
>                   -Ibuild/standalone.gypi --depth=. \
>                   -Dv8_target_arch=x64 \
>                   -S.x64  -Dv8_can_use_vfp_instructions=true
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
>   CXX(target) /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
>
> extconf failed, exit code 1
>
> Gem files will remain installed in /Users/g/.rvm/gems/ruby-2.2.1/gems/libv8-3.11.8.17 for inspection.
> Results logged to /Users/g/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/libv8-3.11.8.17/gem_make.out
>
> I checked what the latest therubyracer version is and that is 0.12.2. I
> can install this version fine after executing gem install libv8 -v
> '3.16.14.13' -- --with-v8-lib, but those are not the versions that work
> for the current Awestruct version.
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/502>.
>


-- 
Sent from Gmail Mobile

**Comment by LightGuard** [comment]
Yep, nothing in awestruct in any of the versions you mentioned depends on libv8 or therubyracer. Must be something in your Gemfile or Gemfile.lock which is causing you to require that gem.

**Comment by galderz** [comment]
Yeah, we've had that `therubyracer` dependency since first version we [created](https://github.com/infinispan/infinispan.github.io/blob/develop/Gemfile). No idea why...

**Comment by LightGuard** [comment]
Are we good to close?

**Comment by galderz** [comment]
Yeah. I've just tried to remove the dependency and it all went well.

**Comment by LightGuard** [comment]
Care to elaborate? There isn't anything in awestruct that uses libv8. Are
you sure you're actually using it? Do you even need it?

On Wed, Feb 24, 2016 at 9:22 AM, Galder Zamarreño <notifications@github.com>
wrote:

> Reopened #502 <https://github.com/awestruct/awestruct/issues/502>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/502#event-563241697>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by galderz** [comment]
LOL, that was coming... I'm in the process of writing...

**Comment by galderz** [comment]
More updates on this. It turns out we use `therubyracer` on `js_minifier` which was an Awestruct extension, see [here](https://github.com/infinispan/infinispan.github.io/blob/develop/_ext/js_minifier.rb). What would be alternative to use to avoid using `therubyracer`?

**Comment by LightGuard** [comment]
Honestly whomever build this transformer did it wrong :) You shouldn't be
creating a new page, it should be changing the content of the page being
passed in, but that doesn't affect libv8. Have you tried increasing the
version of libv8 that you're using? You could try a newer version of
therubyracer.

On Wed, Feb 24, 2016 at 9:24 AM, Galder Zamarreño <notifications@github.com>
wrote:

> More updates on this. It turns out we use therubyracer on js_minifier
> which was an Awestruct extension, see here
> <https://github.com/infinispan/infinispan.github.io/blob/develop/_ext/js_minifier.rb>.
> What would be alternative to use to avoid using therubyracer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/502#issuecomment-188159094>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by galderz** [comment]
@LightGuard Maybe you could help us do things properly?

At the time I tried more recent libv8 libraries but could not get them to work. Next time I have to work with this I'll try again.

**Comment by LightGuard** [comment]
I sent a pull request with some tweaks.

On Wed, Mar 16, 2016 at 4:28 AM, Galder Zamarreño <notifications@github.com>
wrote:

> @LightGuard <https://github.com/LightGuard> Maybe you could help us do
> things properly?
>
> At the time I tried more recent libv8 libraries but could not get them to
> work. Next time I have to work with this I'll try again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/502#issuecomment-197251474>
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp
