### ISSUE TITLE
Page debugging causes unnecessary error

### ISSUE THREAD

**Issue by tristantarrant** [awestruct/awestruct#513]
When building our site (infinispan.github.io) with Awestruct 0.5.7 we get the following stacktrace

An error occurred: no implicit conversion of nil into String
/var/lib/gems/2.2.0/gems/awestruct-0.5.7/lib/awestruct/handlers/javascript_handler.rb:28:in `basename'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7/lib/awestruct/handlers/javascript_handler.rb:28:in `output_filename'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7/lib/awestruct/handlers/base_handler.rb:44:in `output_path'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7/lib/awestruct/page.rb:67:in `output_path'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7/lib/awestruct/page.rb:35:in `inspect'
/var/lib/gems/2.2.0/gems/awestruct-0.5.7/lib/awestruct/page.rb:45:in `inherit_front_matter_from'

Commenting out line 45 in page.rb (which is just a debug log) everything works smoothly.

**Comment by LightGuard** [comment]
How do you not have an output_filename?

**Comment by tristantarrant** [comment]
How should I know ? :)

You can check out the "develop" branch from https://github.com/infinispan/infinispan.github.io and run awestruct on that :)

**Comment by LightGuard** [comment]
I think I have this fixed, but if it creeps back up, let me know.

**Comment by jpechane** [comment]
Hi, we've been bitten by this on Debezium project too. Is there a timeplan for a release with this fix?

Thanks

**Comment by LightGuard** [comment]
@jpechane It should be in the latest release of awestruct.

**Comment by zbynek** [comment]
@jpechane is this still a problem with awestruct 0.6.0-alpha3?
