### ISSUE TITLE
astruct_mixin sometimes tries to undef `entries` on a dynamic class object

### ISSUE THREAD

**Issue by rtyler** [awestruct/awestruct#515]
This is an awful bug report. I've not been able to reproduce this, but sometimes i see the following error when generating [the Jenkins site](/jenkins-infra/jenkins.io)

```
Generating pages...
[0;31;49mAn error during rendering /home/jenkins/root/workspace/jenkins.io/master/content/home/jenkins/root/workspace/jenkins.io/master/content/100k.html.haml occurred.[0m
[0;31;49mWhile processing file /home/jenkins/root/workspace/jenkins.io/master/content/100k.html.haml[0m
[0;31;49mAn error occurred: undefined method 'entries' for class '#<Class:0x6f0e6e5f>'[0m
[0;31;49morg/jruby/RubyModule.java:2671:in `alias_method'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:9:in `singleton class'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:8:in `extended'
org/jruby/RubyKernel.java:1992:in `extend'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:63:in `transform_entry'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:25:in `[]'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/base_tilt_handler.rb:102:in `options'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/base_tilt_handler.rb:131:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/page.rb:143:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:54:in `block in rendered_content'
org/jruby/RubyProc.java:318:in `call'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:40:in `for_layout_chain'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:51:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/page.rb:143:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:381:in `generate_page'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:364:in `block in generate_output'
org/jruby/RubyProc.java:318:in `call'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:288:in `block in work_in_threads'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:419:in `with_instrumentation'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:287:in `block in work_in_threads'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:183:in `block in in_threads'[0m
[0;31;49mPlease see /home/jenkins/root/workspace/jenkins.io/master/content/100k/index.html for more information[0m
[0;31;49mAn error during rendering /home/jenkins/root/workspace/jenkins.io/master/content/home/jenkins/root/workspace/jenkins.io/master/content/blog/2010/2010-02-08-breaking-hudson-1-345-released.md occurred.[0m
[0;31;49mWhile processing file /home/jenkins/root/workspace/jenkins.io/master/content/blog/2010/2010-02-08-breaking-hudson-1-345-released.md[0m
[0;31;49mAn error occurred: undefined method `parse' for Kramdown:Module[0m
[0;31;49m/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/kramdown-1.9.0/lib/kramdown/document.rb:107:in `initialize'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/kramdown.rb:12:in `prepare'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/template.rb:89:in `initialize'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/mapping.rb:136:in `new'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt.rb:43:in `new'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/base_tilt_handler.rb:131:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/page.rb:143:in `rendered_content'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:381:in `generate_page'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:364:in `block in generate_output'
org/jruby/RubyProc.java:318:in `call'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:288:in `block in work_in_threads'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:419:in `with_instrumentation'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:287:in `block in work_in_threads'
/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:183:in `block in in_threads'[0m
[0;31;49mPlease see /home/jenkins/root/workspace/jenkins.io/master/content/blog/2010/02/08/breaking-hudson-1-345-released/index.html for more information[0m
```

I have a hunch this might be related to the `parallel` gem being used, as this machine where we're seeing this, sporadically. has 8 cores compared to my local laptop which has 4 (and never generates the error)

**Comment by LightGuard** [comment]
Have you tried using 0.5.7? If nothing else that will give you a better
error log in .awestruct/error.log

On Tuesday, March 1, 2016, R. Tyler Croy <notifications@github.com> wrote:

> This is an awful bug report. I've not been able to reproduce this, but
> sometimes i see the following error when generating the Jenkins site
> <http:///jenkins-infra/jenkins.io>
>
> Generating pages...
> �[0;31;49mAn error during rendering /home/jenkins/root/workspace/jenkins.io/master/content/home/jenkins/root/workspace/jenkins.io/master/content/100k.html.haml occurred.�[0m
> �[0;31;49mWhile processing file /home/jenkins/root/workspace/jenkins.io/master/content/100k.html.haml�[0m
> �[0;31;49mAn error occurred: undefined method 'entries' for class '#<Class:0x6f0e6e5f>'�[0m
> �[0;31;49morg/jruby/RubyModule.java:2671:in `alias_method'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:9:in `singleton class'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:8:in `extended'
> org/jruby/RubyKernel.java:1992:in `extend'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:63:in `transform_entry'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/astruct_mixin.rb:25:in `[]'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/base_tilt_handler.rb:102:in `options'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/base_tilt_handler.rb:131:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/page.rb:143:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:54:in `block in rendered_content'
> org/jruby/RubyProc.java:318:in `call'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:40:in `for_layout_chain'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:51:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/page.rb:143:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:381:in `generate_page'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:364:in `block in generate_output'
> org/jruby/RubyProc.java:318:in `call'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:288:in `block in work_in_threads'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:419:in `with_instrumentation'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:287:in `block in work_in_threads'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:183:in `block in in_threads'�[0m
> �[0;31;49mPlease see /home/jenkins/root/workspace/jenkins.io/master/content/100k/index.html for more information�[0m
> �[0;31;49mAn error during rendering /home/jenkins/root/workspace/jenkins.io/master/content/home/jenkins/root/workspace/jenkins.io/master/content/blog/2010/2010-02-08-breaking-hudson-1-345-released.md occurred.�[0m
> �[0;31;49mWhile processing file /home/jenkins/root/workspace/jenkins.io/master/content/blog/2010/2010-02-08-breaking-hudson-1-345-released.md�[0m
> �[0;31;49mAn error occurred: undefined method `parse' for Kramdown:Module�[0m
> �[0;31;49m/home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/kramdown-1.9.0/lib/kramdown/document.rb:107:in `initialize'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/kramdown.rb:12:in `prepare'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/template.rb:89:in `initialize'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/mapping.rb:136:in `new'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt.rb:43:in `new'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/base_tilt_handler.rb:131:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/page.rb:143:in `rendered_content'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:381:in `generate_page'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.6/lib/awestruct/engine.rb:364:in `block in generate_output'
> org/jruby/RubyProc.java:318:in `call'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:288:in `block in work_in_threads'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:419:in `with_instrumentation'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:287:in `block in work_in_threads'
> /home/jenkins/root/workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:183:in `block in in_threads'�[0m
> �[0;31;49mPlease see /home/jenkins/root/workspace/jenkins.io/master/content/blog/2010/02/08/breaking-hudson-1-345-released/index.html for more information�[0m
>
> I have a hunch this might be related to the parallel gem being used, as
> this machine where we're seeing this, sporadically. has 8 cores compared to
> my local laptop which has 4 (and never generates the error)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/515>.
>


-- 
Sent from Gmail Mobile

**Comment by rtyler** [comment]
@LightGuard I've seen things *like* this with 0.5.7 (see [this commit](https://github.com/jenkins-infra/jenkins.io/commit/c5e59287ead66d2cdd00cd0aaeb20d3e0157c681)).

I'm going to try monkey-patching the parallel invocation out of here and see what happens there

**Comment by LightGuard** [comment]
Try setting

:generation:
  :in_threads: 0

In your site.yml

On Tuesday, March 1, 2016, R. Tyler Croy <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> I've seen things *like* this
> with 0.5.7 (see this commit
> <https://github.com/jenkins-infra/jenkins.io/commit/c5e59287ead66d2cdd00cd0aaeb20d3e0157c681>
> ).
>
> I'm going to try monkey-patching the parallel invocation out of here and
> see what happens there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/515#issuecomment-190893540>
> .
>


-- 
Sent from Gmail Mobile

**Comment by LightGuard** [comment]
I did say I wasn't support 1.9 anymore :) you can use jruby in 2.0, 2.1 or
2.2 mode depending on the jruby version.

On Tuesday, March 1, 2016, Jason Porter <lightguard.jp@gmail.com> wrote:

> Try setting
>
> :generation:
>   :in_threads: 0
>
> In your site.yml
>
> On Tuesday, March 1, 2016, R. Tyler Croy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @LightGuard <https://github.com/LightGuard> I've seen things *like* this
>> with 0.5.7 (see this commit
>> <https://github.com/jenkins-infra/jenkins.io/commit/c5e59287ead66d2cdd00cd0aaeb20d3e0157c681>
>> ).
>>
>> I'm going to try monkey-patching the parallel invocation out of here and
>> see what happens there
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/awestruct/awestruct/issues/515#issuecomment-190893540>
>> .
>>
>
>
> --
> Sent from Gmail Mobile
>


-- 
Sent from Gmail Mobile

**Comment by rtyler** [comment]
@LightGuard The stacktrace referenced in that commit message was using JRuby 9.0.5.0 and awestruct 0.5.7

The YAML setting is interesting, i'm bringing that in and will see how that works.

**Comment by rtyler** [comment]
A couple consecutive builds in a row, this points me to a load ordering issue or something along those lines with the parallel invocation :-!

**Comment by LightGuard** [comment]
I'd have to see the site and what you're doing that might cause this. Page
generation/rendering is the only thing that happens in parallel.

On Tuesday, March 1, 2016, R. Tyler Croy <notifications@github.com> wrote:

> A couple consecutive builds in a row, this points me to a load ordering
> issue or something along those lines with the parallel invocation :-!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct/issues/515#issuecomment-190917774>
> .
>


-- 
Sent from Gmail Mobile
