### ISSUE TITLE
sassc gem breaks pipeline

### ISSUE THREAD

**Issue by akostadinov** [awestruct/awestruct#535]
```
$ awestruct -P production
Generating site: http://localhost:4242
Executing pipeline...
Generating pages...

$ gem install sassc
Fetching: sassc-1.11.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sassc-1.11.2
Parsing documentation for sassc-1.11.2
Installing ri documentation for sassc-1.11.2
Done installing documentation for sassc after 3 seconds
1 gem installed

$ awestruct -P production
Generating site: http://localhost:4242
Executing pipeline...
Generating pages...
An error during rendering /stylesheets/styles.scss occurred.
While processing file /home/avalon/angelina.jivotvor.com/stylesheets/styles.scss
An error occurred: Error: File to import not found or unreadable: bootstrap.
       Parent style sheet: /home/avalon/angelina.jivotvor.com/stylesheets/styles.scss
        on line 6 of stylesheets/styles.scss
>> @import "bootstrap";
   ^
/home/avalon/angelina.jivotvor.com/stylesheets/styles.scss:6
/home/avalon/.gem/ruby/gems/sassc-1.11.2/lib/sassc/engine.rb:47:in `render'
/home/avalon/.gem/ruby/gems/tilt-2.0.6/lib/tilt/sass.rb:17:in `evaluate'
/home/avalon/.gem/ruby/gems/tilt-2.0.6/lib/tilt/template.rb:100:in `render'
/home/avalon/.gem/ruby/gems/awestruct-0.6.0.alpha/lib/awestruct/handlers/base_tilt_handler.rb:134:in `rendered_content'
/home/avalon/.gem/ruby/gems/awestruct-0.6.0.alpha/lib/awestruct/page.rb:143:in `rendered_content'
/home/avalon/.gem/ruby/gems/awestruct-0.6.0.alpha/lib/awestruct/engine.rb:428:in `generate_page'
/home/avalon/.gem/ruby/gems/awestruct-0.6.0.alpha/lib/awestruct/engine.rb:404:in `block in generate_output'
/home/avalon/.gem/ruby/gems/parallel-1.10.0/lib/parallel.rb:462:in `call_with_index'
/home/avalon/.gem/ruby/gems/parallel-1.10.0/lib/parallel.rb:322:in `block (2 levels) in work_in_threads'
/home/avalon/.gem/ruby/gems/parallel-1.10.0/lib/parallel.rb:473:in `with_instrumentation'
/home/avalon/.gem/ruby/gems/parallel-1.10.0/lib/parallel.rb:321:in `block in work_in_threads'
/home/avalon/.gem/ruby/gems/parallel-1.10.0/lib/parallel.rb:203:in `block (2 levels) in in_threads'
/home/avalon/.gem/ruby/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
Please see .awestruct/error.log for more information
```

**Comment by akostadinov** [comment]
It appears to me that we need to remove a couple of lines under https://github.com/awestruct/awestruct/blob/a101ba9eebd7c9d5ab8daa33fde5b67449e3f428/lib/awestruct/handler_chains.rb#L27
