### ISSUE TITLE
awestruct --init without parameter creates an error

### ISSUE THREAD

**Issue by a4z** [awestruct/awestruct#553]
Hi, 

first, great that there has bee a 0.6.0 release and that the project is still alive.
Thanks for continuing caring about awestruct! 

When I run `awestruct --init` I get an exception, some compass template is not found

```
awestruct --init
Create directory: /home/a4z/work/blog/_config
Create directory: /home/a4z/work/blog/_layouts
Create directory: /home/a4z/work/blog/_ext
Create file: /home/a4z/work/blog/_ext/pipeline.rb
Create file: /home/a4z/work/blog/.awestruct_ignore
Create file: /home/a4z/work/blog/Rakefile
Create directory: /home/a4z/work/blog/stylesheets
Create file: /home/a4z/work/blog/Gemfile
Create file: /home/a4z/work/blog/_config/site.yml
Create file: /home/a4z/work/blog/_layouts/base.html.haml
An error occurred: No such file or directory @ rb_sysopen - /home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/../frameworks/compass/base_layout.html.haml
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:206:in `read'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:206:in `block in perform'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:206:in `open'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:206:in `perform'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:54:in `block in perform'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:53:in `each'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/manifest.rb:53:in `perform'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/init.rb:70:in `run'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/invoker.rb:139:in `invoke_init'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/lib/awestruct/cli/invoker.rb:71:in `invoke!'
/home/a4z/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/awestruct-0.6.0/bin/awestruct:9:in `<top (required)>'
/home/a4z/.asdf/installs/ruby/2.7.1/bin/awestruct:23:in `load'
/home/a4z/.asdf/installs/ruby/2.7.1/bin/awestruct:23:in `<main>'
```

now this is not a real issue, since init with an -f parameter works, but it might irritate new users

**Comment by zbynek** [comment]
Thanks for the report. This issue was introduced when the `-f compass` option was removed, but `compass` was kept the default framework. The quick fix would be to make `bootstrap` the new default, but that requires a bunch of other gems to be installed, some of them (like `sass`) are deprecated and dead. I'll check if we can have `init` that would not add any frameworks by default.

**Comment by a4z** [comment]
this seems to be solved in the latest releases, so I close this therefore
