### ISSUE TITLE
engine.site.pages_by_output_path is nil in lib/awestruct/rack/generate.rb

### ISSUE THREAD

**Issue by l7rf1i82** [awestruct/awestruct#558]
### Hello, how i can fix this problem:

```
[2021-09-28 15:38:30] ERROR NoMethodError: undefined method `[]' for nil:NilClass
	/var/lib/gems/2.7.0/gems/awestruct-0.6.1/lib/awestruct/rack/generate.rb:19:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
	/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/var/lib/gems/2.7.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
	/var/lib/gems/2.7.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
	/var/lib/gems/2.7.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
	/var/lib/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
localhost - - [28/Sep/2021:15:38:30 UTC] "GET / HTTP/1.0" 500 318
```
I exec:
```
$ awestruct --init --framework bootstrap
```
Then exec:
```
$ rake
```
and did GET request from browser

### My Gemfile:

```
gem 'awestruct', '>= 0.6.1'                               # Goes without saying
gem 'webrick', '~> 1.3.1'                                 # The rack webserver to use in dev mode

gem 'bootstrap-sass', '>= 3.2.0.2'
gem 'compass', '>= 1.0.1'

# FIXME
# gem 'rake', '>= 0.9.2'                                  # Needed for the Rakefile to work
# gem 'coffee-script', '>= 2.2.0'                         # If using coffee-script or to remove the warning
# gem 'rb-fsevent', '~> 0.9', :require => false           # to remove warning about pulling, Mac OSX
# gem 'rb-inotify', '>= 0.9.0', :require => false         # to remove warning about pulling, Linux
# gem 'wdm', :platforms => [:mswin, :mingw], :require => false # to remove warning about pulling, Windows (ruby 1.9+)
# gem 'rb-fchange', '~> 0.0.6', :require => false         # to remove warning about pulling, Windows (ruby 1.8.7)
# gem 'therubyracer', '0.10.0', :platforms => :ruby       # Javascript runtime on mri (needed for LESS and coffee-script)
# gem 'therubyrhino', '~> 2.0.2', :platforms => :jruby    # Javascript runtime on jruby (needed for LESS and coffee-script)
# gem 'less', '>= 2.2.2'                                  # If using LESS instead of sass
# gem 'org-ruby', '>= 0.8'                                # If using Org-Mode
# gem 'RedCloth', '>= 4.2.9'                              # If using Textile
# gem 'asciidoctor', '>= 0.1.1'                           # If using AsciiDoc syntax, need 0.1.1 for Header support
# gem 'slim', '>= 1.3.6'                                  # If using slim instead of haml
# gem 'kramdown', '>= 0.14.2'                             # If using Markdown
gem 'uglifier', '>= 1.3.0'                              # If using the minify transformer
gem 'htmlcompressor', '>= 0.0.3'                        # If using the minify transformer
gem 'opal'
```

**Comment by l7rf1i82** [comment]
This solution solve my problem:
[https://github.com/middleman/middleman/issues/2139#issuecomment-356795667](https://github.com/middleman/middleman/issues/2139#issuecomment-356795667)

**Comment by l7rf1i82** [comment]
in Gemfile insert:
```gem 'opal', '~> 0.10.5'```
exec:
```$ rake update```
exec:
```$ rake```
